--KIỂM TRA BẢNG NHANVIEN ĐÃ TỒN TẠI
--NOT NULL: RÀNG BUỘC DỮ LIỆU KHÔNG ĐƯỢC ĐỂ TRỐNG
--PRIMARY KEY: ĐÁNH DẤU TRƯỜNG DỮ LIỆU VÀ KHÓA CHÍNH
-- FOREIGN KEY: ĐÁNH DẤU TRƯỜNG DỮ LIỆU VÀ KHÓA PHỤ
IF OBJECT_ID('NHANVIEN') IS NOT NULL
	DROP TABLE NHANVIEN --THÌ SẼ XÓA BẢNG NHANVIEN
GO
CREATE TABLE NHANVIEN (
	HONV nvarchar(15) NOT NULL, 
	TENLOT nvarchar(15) NOT NULL,
	TENNV nvarchar(15) NOT NULL,
	MANV nvarchar(9) PRIMARY KEY NOT NULL,
	NGSINH datetime NOT NULL,
	DCHI nvarchar(30) NOT NULL,
	PHAI nvarchar(30) NOT NULL,
	LUONG float NOT NULL,
	MA_NQL nvarchar(9),
	PHG int,
	
)

--TẠO BẢNG PHONGBAN
IF OBJECT_ID('PHONGBAN') IS NOT NULL
	DROP TABLE PHONGBAN
GO
CREATE TABLE PHONGBAN(
	TENPHG nvarchar(15) NOT NULL,
	MAPHG int PRIMARY KEY NOT NULL,
	TRPHG nvarchar(9),
	NG_NHANCHUC date NOT NULL,
	FOREIGN KEY(TRPHG) REFERENCES NHANVIEN,
)


-- KHÓA PHỤ PHG LIÊN QUAN ĐẾN BẢNG PHONGBAN
	ALTER TABLE NHANVIEN ADD FOREIGN KEY (PHG) 
	REFERENCES PHONGBAN;
	ALTER TABLE NHANVIEN ADD FOREIGN KEY (MA_NQL) 
	REFERENCES NHANVIEN;
