IF OBJECT_ID('KHACHHANG') IS NOT NULL
	DROP TABLE KHACHHANG
GO
CREATE TABLE KHACHHANG (
	MAKH varchar(10) PRIMARY KEY NOT NULL,
	TENKH nvarchar(20) NOT NULL,
	TAIKHOAN nvarchar(20) NOT NULL,
)
IF OBJECT_ID('DATHANG') IS NOT NULL
	DROP TABLE DATHANG
GO
CREATE TABLE DATHANG (
	MADATHANG varchar(10) PRIMARY KEY NOT NULL,
	MAKH varchar(10) NOT NULL,
	MASACH varchar(10) NOT NULL,
	SOLUONG int NOT NULL,
	DONGIA int NOT NULL,
)
ALTER TABLE DATHANG ADD FOREIGN KEY(MAKH) REFERENCES KHACHHANG

INSERT INTO KHACHHANG(MAKH, TENKH, TAIKHOAN) VALUES('A01','ToanNK','000502001')
INSERT INTO KHACHHANG(MAKH, TENKH, TAIKHOAN) VALUES('A02','VanNT','000745001')	
INSERT INTO KHACHHANG(MAKH, TENKH, TAIKHOAN) VALUES('A03','TrangTT','000341928')

INSERT INTO DATHANG(MADATHANG, MAKH, MASACH, SOLUONG, DONGIA) VALUES('DT01', 'A01', 'S01', 10, 50000)
INSERT INTO DATHANG(MADATHANG, MAKH, MASACH, SOLUONG, DONGIA) VALUES('DT02', 'A01', 'S02', 9, 30000)
INSERT INTO DATHANG(MADATHANG, MAKH, MASACH, SOLUONG, DONGIA) VALUES('DT03', 'A02', 'S03', 7, 70000)


SELECT MAKH,TENKH FROM KHACHHANG
SELECT MaDatHang, MaKH, Soluong, Dongia,(Soluong * Dongia)AS THANHTIEN FROM DATHANG
SELECT TENKH FROM KHACHHANG WHERE TAIKHOAN LIKE '%01'
SELECT * FROM KHACHHANG WHERE TENKH LIKE 'T%'
SELECT SUM(SOLUONG),MAKH FROM DATHANG GROUP BY MAKH HAVING SUM(SOLUONG) >=10 ORDER BY SOLUONG ASC 
SELECT MAX(SOLUONG) FROM DATHANG 
 
