--CÂU TRUY VẤN ĐƠN GIẢN LẤY RA TẤT CẢ CÁC CỘT TRONG BẢNG	
-- SELECT * FROM + TÊN BANGR
SELECT * FROM NHANVIEN
SELECT * FROM CONGVIEC

--LẤY RA DỮ LIỆU CÁC CỘT XÁC ĐỊNH
--SELECT cot1, cot2,... FROM + TÊN BẢNG
SELECT HONV, TENNV FROM NHANVIEN

--LOẠI BỎ GIÁ TRỊ TRÙNG LẶP VỚI DISTINCT	
--TRẢ VỀ CÁC BẢN GHI CÓ GIÁ TRỊ KHÔNG TRÙNG LẶP ÁP DỤNG VỚI CỘT DỮ LIỆU ĐẦU TIÊN
SELECT DISTINCT TENNV FROM NHANVIEN

--TRUY VẤN KẾT HỢP MỆNH ĐỀ WHERE
--LẤY RA TẤT CẢ NHÂN VIÊN CÓ HỌ TRẦN
SELECT * FROM NHANVIEN WHERE HONV = N'Trần'

SELECT * FROM NHANVIEN WHERE MANV IN ('001', '002', '005')

SELECT * FROM NHANVIEN WHERE TENNV = N'Tùng' AND HONV = N'Nguyễn'

SELECT * FROM NHANVIEN WHERE TENNV = N'Tùng' OR HONV = N'Nguyễn'