--CÂU TRUY VẤN ĐƠN GIẢN LẤY RA TẤT CẢ CÁC CỘT TRONG BẢNG	
-- SELECT * FROM + TÊN BANGR
SELECT * FROM NHANVIEN
SELECT * FROM CONGVIEC

--LẤY RA DỮ LIỆU CÁC CỘT XÁC ĐỊNH
--SELECT cot1, cot2,... FROM + TÊN BẢNG
SELECT HONV, TENNV FROM NHANVIEN

--LOẠI BỎ GIÁ TRỊ TRÙNG LẶP VỚI DISTINCT	
--TRẢ VỀ CÁC BẢN GHI CÓ GIÁ TRỊ KHÔNG TRÙNG LẶP ÁP DỤNG VỚI CỘT DỮ LIỆU ĐẦU TIÊN
SELECT DISTINCT TENNV FROM NHANVIEN

--TRUY VẤN KẾT HỢP MỆNH ĐỀ WHERE
--LẤY RA TẤT CẢ NHÂN VIÊN CÓ HỌ TRẦN
SELECT * FROM NHANVIEN WHERE HONV = N'Trần'

SELECT * FROM NHANVIEN WHERE MANV IN ('001', '002', '005')

SELECT * FROM NHANVIEN WHERE TENNV = N'Tùng' AND HONV = N'Nguyễn'

SELECT * FROM NHANVIEN WHERE TENNV = N'Tùng' OR HONV = N'Nguyễn'

SELECT * FROM NHANVIEN WHERE MANV IN ('001', '002', '005') AND LUONG>=40000

SELECT * FROM NHANVIEN WHERE MANV IN ('001', '002', '005') AND LUONG>=40000 OR PHAI = N'Nam'

SELECT * FROM NHANVIEN WHERE MANV IN ('001', '002', '005') OR PHAI = N'Nam' AND LUONG>=40000 

--ĐIỀU KIỆN WHERE BETWEEN
SELECT * FROM NHANVIEN WHERE LUONG BETWEEN 20000 AND 35000
SELECT * FROM NHANVIEN WHERE NGSINH BETWEEN '1960-01-01' AND '1965-12-30'

--ĐIỀU KIỆN WHERE LIKE
--LẤY RA TẤT CẢ CỘT CÓ TENNV GIỐNG KÝ TỰ 'TÙNG'
SELECT * FROM NHANVIEN WHERE TENNV LIKE N'Tùng'
--LẤY RA TẤT CẢ CÁC CỘT CỦA BẢNG NHANVIEN CÓ TÊN NV BẮT ĐẦU BẰNG KÝ TỰ 'T'
SELECT * FROM NHANVIEN WHERE TENNV LIKE 'T%'
SELECT * FROM NHANVIEN WHERE DCHI LIKE '119%'
--LẤY RA TẤT CẢ CÁC CỘT CỦA BẢNG NHANVIEN CÓ TÊN NV KẾT THÚC BẰNG KÝ TỰ 'N'
SELECT * FROM NHANVIEN WHERE TENNV LIKE '%N'
SELECT * FROM NHANVIEN WHERE DCHI LIKE '%TP HCM'
--LẤY RA TẤT CẢ CÁC CỘT CỦA BẢNG NHANVIEN ĐỊA CHỈ CÓ KÝ TỰ 'CỐNG QUỲNH'
SELECT * FROM NHANVIEN WHERE DCHI LIKE N'%Cống Quỳnh%'
--
SELECT *FROM NHANVIEN WHERE HONV LIKE 'T___'
SELECT *FROM NHANVIEN WHERE TENNV LIKE '_I%'

----
--SELECT [DISTINCT] COLUMN(S) FROM + TÊN BẢNG + [WHERE ĐIỀU KIỆN] 
--[ORDER BY TÊN CỘT[ASC/DESC]] 
--[GROUP BY] [HAVING ĐK NHÓM]

--ORDER BY: SẮP XẾP
SELECT * FROM NHANVIEN ORDER BY LUONG ASC

SELECT * FROM NHANVIEN ORDER BY LUONG DESC
--GROUP BY: NHÓM CÁC DỮ LIỆU CÓ GIÁ TRỊ GIỐNG NHAU THÀNH MỘT NHÓM
SELECT PHG, MAX(LUONG) AS LUONG_MAX FROM NHANVIEN GROUP BY PHG
--HÀM TỔNG HỢP: TÊN HÀM (TÊN CỘT)
--MAX(CỘT): TÌM RA GTLN
--MIN(CỘT): TÌM RA GTNN
--AVG(CỘT): TÌM RA GIÁ TRỊ TB
--COUNT(CỘT):ĐẾM SỐ LƯỢNG
SELECT PHG, MIN(LUONG) LUONG_MIN FROM NHANVIEN GROUP BY PHG HAVING MIN(LUONG) > 25000
SELECT MAX(NGSINH) AS NGSINH_MAX FROM NHANVIEN
SELECT COUNT(*) AS SOLUONG FROM NHANVIEN
SELECT COUNT(MANV) AS SOLUONGNV FROM NHANVIEN
--ĐẶT LẠI TÊN CÁC CỘT QUA KEYWORDS
SELECT HONV AS HONHANVIEN, TENLOT AS TENLOTNHANVIEN, TENNV AS TENNHANVIEN FROM NHANVIEN
--THỰC HIÊN PHÉP TÍNH DỰA VÀO CÁC CỘT 
SELECT TENNV, (LUONG * 12) AS TONGTHUNHAP FROM NHANVIEN 
SELECT HONV, TENNV, (YEAR(GETDATE())-YEAR(NGSINH)) AS TUOI FROM NHANVIEN
SELECT TENNV, ((LUONG + 1000) * 12) AS TONGTHUNHAP FROM NHANVIEN WHERE PHAI = N'NỮ'

